/**
 * Emits the ambient declaration for the `vite-mat-symbols` virtual module.
 *
 * Everything else the plugin needs is derived from the `.codepoints` file at
 * runtime; types are the one thing that cannot be, so this is the only
 * generated artifact in the package.
 *
 * Run with: nx run vite-material-symbols:generate-types
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadIconTable } from '../src/icons.ts';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'client.d.ts');

const { exports } = loadIconTable();
const names = [...exports.keys()].sort();

const body = names.map((n) => `  export const ${n}: MaterialSymbolComponent;`).join('\n');

const dts = `// Generated by scripts/generate-types.ts — do not edit.
// ${names.length} icons.

declare module 'vite-mat-symbols' {
  import type { SymbolProps } from 'vite-material-symbols/runtime';

  export type MaterialSymbolComponent = (props: SymbolProps) => JSX.Element;

${body}
}

declare module 'vite-mat-symbols:*' {
  import type { SymbolProps } from 'vite-material-symbols/runtime';

  const symbol: (props: SymbolProps) => JSX.Element;
  export default symbol;
}
`;

writeFileSync(out, dts, 'utf8');
console.log(`wrote ${out} (${names.length} icons, ${(dts.length / 1024).toFixed(0)} KB)`);
